### ISSUE TITLE
Basic Animation Transition & Transforms Improvements

### ISSUE THREAD

**Issue by FMCalisto** [mida-project/prototype-multi-modality-assistant#13]
The development of an *Assistant* helps the automation of cancer diagnosis. If a large dataset is available, it is possible to have recommendation methodologies that automatically can classify the set of medical images and lesions detection, giving a high probability to those cases where intervention is necessary. These methodologies will bring us a high impact to the clinical field. Such automation is crucial since it reduces the inspection performed by the radiologist, that is still rudimentary in current clinical setups. Besides having large datasets, the follow-up of the patient is crucial. This dataset means that the annotation of a given patient should be analyzed through time.

Based on the literature we plan to improve our *Assistant* within a context of scaling our solution. We aim to understand how clinical institutions can use our system with impactful healthcare systems.

In this set of issues, our requirements are as follows. A fourfold of conditions must be addressed across the final solution. We aim to achieve some visual improvements to our *Assistant* animations, more detailed below.

List of enhancing features from post-testing phases:

- [x] Transition Property Improvements #9

- [x] Transition Duration Improvements #10

- [ ] Transition Timing Improvements #11

- [ ] Transform Improvements #12
